### ISSUE TITLE
Improve docs for extending SonataUserBundle e.g. how to override User services and add Child

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataEasyExtendsBundle#55]
Recentely I had to override the Sonata Admin User Admin Class and add a Child `Payroll` to the User Entity.

I simply copied the original `Resources/config/admin_orm.xml`file from the vendor UserBundle to my `Application\Sonata\UserBundle` and it works fine:

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <parameters>
        <parameter key="sonata.user.admin.groupname">sonata_user</parameter>
    </parameters>

    <services>
        <service id="sonata.user.admin.user" class="%sonata.user.admin.user.class%">
            <tag name="sonata.admin" manager_type="orm" group="%sonata.user.admin.groupname%" label="users" label_catalogue="SonataUserBundle" label_translator_strategy="sonata.admin.label.strategy.underscore" />
            <argument />
            <argument>%sonata.user.admin.user.entity%</argument>
            <argument>%sonata.user.admin.user.controller%</argument>
            <call method="setUserManager">
                <argument type="service" id="fos_user.user_manager" />
            </call>
            <call method="setTranslationDomain">
                <argument>%sonata.user.admin.user.translation_domain%</argument>
            </call>
            <call method="addChild">
                <argument type="service" id="sonata.admin.payroll" />
            </call>            
        </service>

        <service id="sonata.user.admin.group" class="%sonata.user.admin.group.class%">
            <tag name="sonata.admin" manager_type="orm" group="%sonata.user.admin.groupname%" label="groups" label_catalogue="SonataUserBundle"  label_translator_strategy="sonata.admin.label.strategy.underscore" />
            <argument />
            <argument>%sonata.user.admin.group.entity%</argument>
            <argument>%sonata.user.admin.group.controller%</argument>
            <call method="setTranslationDomain">
                <argument>%sonata.user.admin.group.translation_domain%</argument>
            </call>
        </service>
    </services>
</container>

```

I don't know if this is best practice since I havn't found any docs on this.

For instance how to override if I want to use YAML instead of XML? Override the services for `sonata.user.admin.user`?

``` yaml
services:
    sonata.user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label_catalogue: "messages", label: "Users"}
        arguments:
            - ~
            - Application\Sonata\UserBundle\Entity\User
            - ~    
        calls:
            - [ addChild, [ @sonata.admin.payroll ] ]    
```

Maybe these steps could be added to docs as recipes:
http://sonata-project.org/bundles/easy-extends/master/doc/reference/why.html

Any thoughts?
